# version: '3.7'
# services:
#   gowebserver:
#     build: .
#     # restart: 'on-failure'
#     # network_mode: 'host'
#     container_name: go-project-backend
#     env_file:
#       - './.env'
#     ports:
#       - '8010'

# # git --work-tree=/var/www/x  --git-dir=/var/git_repo/x.git checkout -f

version: '3.7'
services:
  gowebserver:
    build: '.'
    expose:
      - '8010'
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Africa/Lagos
      - API_PORT=8010
      - API_SECRET=ab1234
      - DB_DRIVER=postgres
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=sommysab
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ENV=production
  nginx:
    build: './nginx'
    ports:
      - '80:80'
    depends_on:
      - 'gowebserver'
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres
