version: '3.7'
services:
  api:
    build: .
    restart: on-failure
    network_mode: 'host'
    container_name: go-project-backend
    #
    # volumes:
    #   - .:/app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Africa/Lagos
    logging:
      options:
        max-size: '10m'
        max-file: '3'
