version: '3.7'
services:
  api:
    build: .
    restart: 'on-failure'
    network_mode: 'host'
    container_name: go-project-backend
    env_file:
      - './.env'
    ports:
      - '8000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Africa/Lagos
      - API_PORT=8000
      - API_SECRET=ab1234
      # DATABASE CONFIG
      - DB_DRIVER=mysql
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=sammy
      - DB_PASSWORD=some_ABC_pass_123
      - DB_NAME=blog
      - ENV=production
    logging:
      options:
        max-size: '10m'
        max-file: '3'
  nginx:
    build: './nginx'
    ports:
      - '8000:80'
    depends_on:
      - 'api'
