# version: '3.7'
# services:
#   gowebserver:
#     build: .
#     # restart: 'on-failure'
#     # network_mode: 'host'
#     container_name: go-project-backend
#     env_file:
#       - './.env'
#     ports:
#       - '8010'

# # git --work-tree=/var/www/x  --git-dir=/var/git_repo/x.git checkout -f

version: '3'
services:
  # postgres:
  #   image: 'postgres:latest'
  #   environment:
  #     - POSTGRES_PASSWORD=mypostgres
  db:
    image: mysql:5.7.26
    restart: always
    container_name: godockerDB
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: godocker
    ports:
      - '3307:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
  gowebserver:
    build: '.'
    restart: always
    expose:
      - '8010'
    depends_on:
      - db
    links:
      - db
    environment:
      # - CHOKIDAR_USEPOLLING=true
      # - TZ=Africa/Lagos
      - API_PORT=8010
      - API_SECRET=ab1234
      - DB_DRIVER=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=@root
      - DB_NAME=blog
      - ENV=production
  nginx:
    build: './nginx'
    ports:
      - '80:80'
    depends_on:
      - 'gowebserver'
