# git --work-tree=/var/www/x  --git-dir=/var/git_repo/x.git checkout -f
version: '3.7'
services:
  db:
    image: mysql:5.7.26
    container_name: godockerDB
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: passwor1d
      MYSQL_PASSWORD: passwor1d
      MYSQL_DATABASE: godocker
    ports:
      - '3306:3306'
  gowebserver:
    build: '.'
    restart: always
    expose:
      - '8010'
    depends_on:
      - db
    links:
      - db
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Africa/Lagos
      - API_PORT=8010
      - API_SECRET=ab1234
      - DB_DRIVER=mysql
      - DB_NAME=godocker
      - DB_USER=docker
      - DB_PASSWORD=passwor1d
      - ENV=production
  nginx:
    build: './nginx'
    restart: always
    ports:
      - '80:80'
    depends_on:
      - 'gowebserver'
