version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=que-machano.com
      - LETSENCRYPT_HOST=que-machano.com
