version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    network_mode: 'host'
    container_name: go-project-backend
    env_file:
      - '.env'
    environment:
      - VIRTUAL_HOST=que-machano com
      - LETSENCRYPT_HOST=que-machano.com
      - API_PORT=8000
      - API_SECRET=ab1234
      # DATABASE CONFIG
      - DB_DRIVER=mysql
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=sammy
      - DB_PASSWORD=some_ABC_pass_123
      - DB_NAME=blog
      - ENV=production
