version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - '.env'
    environment:
      - VIRTUAL_HOST=que-machano com
      - LETSENCRYPT_HOST=que-machano.com
      - API_PORT=8000
      - API_SECRET=ab1234
      # DATABASE CONFIG
      - DB_DRIVER=mysql
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=sommysab
      - DB_PASSWORD=N?c$=u_A5aGz&n?E7@3c7
      - DB_NAME=blog2
      - ENV=production
